[package]
name = "bountive"
version = "0.1.0"
description = "Core contracts of the Bountive Protocol"
homepage = ""

[dependencies]
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts" }
starknet = ">=2.3.1"

[[target.starknet-contract]]
name = "bountive"
sierra = true
casm = true
